manuscript:
  props:
    - PLAY_REMOTEREPO:   origin
    - PLAY_TARGETBRANCH: master
    - PLAY_REMOTEBRANCH: '`echo $PLAY_REMOTEREPO/$PLAY_TARGETBRANCH`'
  scene:
    dryrun: 1
    verbose: true
    debug:   1
  parts:
    integrate:
      props:
        - PLAY_VERSION:      ${CIRCLE_SHA1:=`git rev-parse HEAD`}
        - PLAY_VER:          '`printenv PLAY_VERSION | cut -c 1-7`'
        - PLAY_TARGETVER:    '`git rev-parse --short $PLAY_REMOTEBRANCH`'
      scene:
        verbose: 0
        dryrun: 0
        debug: 0
      lines:
        - run:
          caption: Rebase
          command: git rebase $REMOTEBRANCH
        - run:
          name:    Checkout
          command: git checkout $TARGETBRANCH
        - run:
          name:    Pull
          command: git pull $REMOTEREPO $TARGETBRANCH
