
version: 2
jobs:

  integrate:
    working_directory: /app
    # The primary container is an instance of the first list image listed. Your build commands run in this container.
    docker:
      - image: lakruzz/jekyll-plus:1.0.1
    environment:
      CIRCLE_BRANCH: $CIRCLE_BRANCH
    steps:
      - checkout
      - run:
          name: git version
          command: git --version
      - run:
          name: Circle CI environment
          command: 'env | sort | grep "CIRCLE"'
      - run:
          name: Rebase to master
          command: git rebase master
      - run:
          name: Checkout integration branch
          command: git checkout master
      - run:
          name: Get the Symbolich name of HEAD
          command: git rev-parse --abbrev-ref HEAD
      - run:
          name: Merge in the dev-branch
          command: |
            git merge --ff-only $CIRCLE_BRANCH
            echo $CIRCLE_BRANCH



  build:
    working_directory: /app
    # The primary container is an instance of the first list image listed. Your build commands run in this container.
    docker:
      - image: lakruzz/jekyll-plus:1.0.1
    steps:
      - checkout
      - run:
          name: Jekyll
          command: jekyll build
      - save_cache:
          key: the-site-{{ .Revision }}
          paths:
            - _site

  test:
    working_directory: /app
    docker:
      - image: 18fgsa/html-proofer
    steps:
      - restore_cache:
          keys:
            - the-site-{{ .Revision }}

      - run:
          name: List
          command: 'ls'
      - run:
          name: Htmlproofer
          command: htmlproofer --disable-external --allow-hash-href --checks-to-ignore ImageCheck --check-favicon _site

workflows:
  version: 2
  build_and_test:
    jobs:
      - integrate
#      - build
#      - test:
#          requires:
#            - build
