
version: 2
jobs:

  integrate:
    working_directory: /app
    # The primary container is an instance of the first list image listed.
    # Your build commands run in this container.
    docker:
      - image: lakruzz/jekyll-plus:1.0.1
    steps:
      - checkout
      - run:
          name: Environment
          command: |
            git --version
            env | sort | grep "CIRCLE"
      - run:
          name: Intro
          command: ./play -part gitintro
      - run:
          name: Swap to target branch and test integration
          command: ./play --manuscript .circleci/manuscript.yml --part integrate

  build:
    working_directory: /app
    docker:
      - image: lakruzz/jekyll-plus:1.0.1
    steps:
      - checkout
      - run:
          name: Swap to target branch and integrate
          command: ./play --manuscript .circleci/manuscript.yml --part integrate
      - run:
          name: Where am I
          command: |
            pwd
            ls -a
            git rev-parse --short HEAD
      - run:
          name: Jekyll
          command: jekyll build
      - save_cache:
          key: the-site-{{ .Revision }}
          paths:
            - _site

  test:
    working_directory: /app
    docker:
      - image: 18fgsa/html-proofer
    steps:
      - restore_cache:
          keys:
            - the-site-{{ .Revision }}
      - run:
          name: Htmlproofer
          command: htmlproofer --disable-external --allow-hash-href --checks-to-ignore ImageCheck --check-favicon _site

  deliver:
    working_directory: /app
    docker:
      - image: lakruzz/jekyll-plus:1.0.1
    steps:
      - checkout
      - run:
          name: Intro
          command: ./play --manuscript .circleci/manuscript.yml --part gitintro
      - run:
          name: integrate
          command: ./play --manuscript .circleci/manuscript.yml --part integrate
      - run:
          name: Deliver
          command: ./play --manuscript .circleci/manuscript.yml --part deliver

workflows:
  version: 2
  jekyll_phlow:
    jobs:
      - integrate:
          filters:
            branches:
              only:
                - /ready\/.*/
      - build:
          requires:
            - integrate
      - test:
          requires:
            - build
      - deliver:
          requires:
            - test
