
version: 2
jobs:

  integrate:
    working_directory: /app
    # The primary container is an instance of the first list image listed. Your build commands run in this container.
    docker:
      - image: lakruzz/jekyll-plus:1.0.1
    steps:
      - checkout
      - run:
          name: git version
          command: git --version
      - run:
          name: Circle CI environment
          command: 'env | sort | grep "CIRCLE"'
      - run:
          name: Swap to master and integrate
          command: .circleci/integrate.sh
      - save_cache:
          key: integrated-{{ .BuildNum }}
          paths:
            - ".git"
            - "version.txt"

  build:
    working_directory: /app
    # The primary container is an instance of the first list image listed. Your build commands run in this container.
    docker:
      - image: lakruzz/jekyll-plus:1.0.1
    steps:
      - restore_cache:
          keys:
            - integrated-{{ .BuildNum }}
      - run:
          name: Jekyll
          command: jekyll build
      - save_cache:
          key: the-site-{{ .BuildNum }}
          paths:
            - _site

  test:
    working_directory: /app
    docker:
      - image: 18fgsa/html-proofer
    steps:
      - restore_cache:
          keys:
            - the-site-{{ .BuildNum }}
      - run:
          name: Htmlproofer
          command: htmlproofer --disable-external --allow-hash-href --checks-to-ignore ImageCheck --check-favicon _site

workflows:
  version: 2
  build_and_test:
    jobs:
      - integrate
      - build:
          requires:
            - integrate
      - test:
          requires:
            - build
