
version: 2
jobs:

  integrate:
    name: Validate integration
    working_directory: /app
    # The primary container is an instance of the first list image listed. Your build commands run in this container.
    docker:
      - image: lakruzz/jekyll-plus:1.0.1
    steps:
      - checkout
      - run:
          name: Environment
          command: |
            git --version
            env | sort | grep "CIRCLE"
      - run:
          name: Swap to master and integrate
          command: .circleci/integrate.sh

  build:
    working_directory: /app
    # The primary container is an instance of the first list image listed. Your build commands run in this container.
    docker:
      - image: lakruzz/jekyll-plus:1.0.1
    steps:
      - checkout
      - run:
          name: Swap to master and integrate
          command: .circleci/integrate.sh
      - run:
          name: Where am I
          command: |
            git status
            ls -a
            cat version.txt
            git rev-parse --short HEAD
      - run:
          name: Jekyll
          command: jekyll build
      - save_cache:
          key: the-site-{{ .Revision }}
          paths:
            - _site

  test:
    working_directory: /app
    docker:
      - image: 18fgsa/html-proofer
    steps:
      - restore_cache:
          keys:
            - the-site-{{ .Revision }}
      - run:
          name: Htmlproofer
          command: htmlproofer --disable-external --allow-hash-href --checks-to-ignore ImageCheck --check-favicon _site

workflows:
  version: 2
  build_and_test:
    jobs:
      - integrate
      - build:
          requires:
            - integrate
      - test:
          requires:
            - build
