
version: 2
jobs:

  validate_integration:
    working_directory: /app
    # The primary container is an instance of the first list image listed. Your build commands run in this container.
    docker:
      - image: lakruzz/jekyll-plus:1.0.1
    steps:
      - checkout
      - run:
          name: Environment
          command: |
            git --version
            env | sort | grep "CIRCLE"
      - run:
          name: Validate state
          command: .circleci/validate-state.sh
      - run:
          name: Swap to target branch and test integration
          command: .circleci/integrate.sh

  build:
    working_directory: /app
    # The primary container is an instance of the first list image listed. Your build commands run in this container.
    docker:
      - image: lakruzz/jekyll-plus:1.0.1
    steps:
      - checkout
      - run:
          name: Swap to target branch and integrate
          command: .circleci/integrate.sh
      - run:
          name: Write the repo name and version to file
          command: .circleci/write-version.sh
      - run:
          name: Where am I
          command: |
            pwd
            ls -a
            git rev-parse --short HEAD
      - run:
          name: Jekyll
          command: jekyll build
      - save_cache:
          key: the-site-{{ .Revision }}
          paths:
            - _site

  test:
    working_directory: /app
    docker:
      - image: 18fgsa/html-proofer
    steps:
      - restore_cache:
          keys:
            - the-site-{{ .Revision }}
      - run:
          name: Htmlproofer
          command: htmlproofer --disable-external --allow-hash-href --checks-to-ignore ImageCheck --check-favicon _site

workflows:
  version: 2
  ready_for_jekyll:
    jobs:
      - integrate
      - build:
          requires:
            - integrate
      - test:
          requires:
            - build
