manuscript:
  props:
    - PLAY_REMOTEREPO:   origin
    - PLAY_TARGETBRANCH: master
    - PLAY_REMOTEBRANCH: '`echo $PLAY_REMOTEREPO/$PLAY_TARGETBRANCH`'
  scene:
    dryrun:  0
    verbose: 0
    debug:   0
  parts:
    integrate:
      props:
        - PLAY_VERSION:      ${CIRCLE_SHA1:=`git rev-parse HEAD`}
        - PLAY_VER:          '`printenv PLAY_VERSION | cut -c 1-7`'
        - PLAY_TARGETVER:    '`git rev-parse --short $PLAY_REMOTEBRANCH`'
      scene:
        verbose: 0
        dryrun: 1
        debug: 0
      lines:
        - run:
            caption: Rebase to remote branch
            command: git rebase $PLAY_REMOTEBRANCH
            die_on_err: yes
        - run:
            caption: Checkout target branch
            command: git checkout $PLAYS_TARGETBRANCH
            die_on_err: yes
        - run:
            caption: Pull latest
            command: git pull $PLAY_REMOTEREPO $PLAY_TARGETBRANCH
            die_on_err: yes
        - run:
            caption: Merge
            command: git merge --ff-only $PLAY_VER
            die_on_err: yes
    deploy:
      props:
      scene:
    deliver:
      props:
        - PLAY_GITREPO: '`git remote get-url  $PLAY_REMOTEREPO | sed  s/".*github.com[\/:]//" | sed s/.git//`'
      scene:
        dryrun:  no
        verbose: yes
      lines:
        - run:
            caption:
            command: git config user.name "Circle CI by @Lakruzz"
            die_on_err: yes
        - run:
            caption:
            command: git config user.email "circleci@lakruzz.com"
            die_on_err: yes
        - run:
            caption:
            command: git remote add ghtoken https://$GHTOKEN@github.com/$PLAY_GITREPO.git
            die_on_err: yes--part integrate
        - run:
            caption:
            command: git push ghtoken
            die_on_err: yes
        - run:
            caption:
            command: git push ghtoken :$CIRCLE_BRANCH
            die_on_err: yes
