manuscript:
  props:
    - PLAY_REMOTEREPO:   origin
    - PLAY_TARGETBRANCH: master
    - PLAY_REMOTEBRANCH: '`echo $PLAY_REMOTEREPO/$PLAY_TARGETBRANCH`'
  scene:
    dryrun: 1
    verbose: true
    debug:   yes
  parts:
    integrate:
      props:
        - PLAY_VERSION:      ${CIRCLE_SHA1:=`git rev-parse HEAD`}
        - PLAY_VER:          '`printenv PLAY_VERSION | cut -c 1-7`'
        - PLAY_TARGETVER:    '`git rev-parse --short $PLAY_REMOTEBRANCH`'
      scene:
        verbose: 0
        dryrun: 1
        debug: 0
      lines:
        - run:
            caption: Rebase to remote branch
            command: git rebase $PLAY_REMOTEBRANCH
            die_on_err: yes
        - run:
            caption: Checkout target branch
            command: git checkout $PLAYS_TARGETBRANCH
        - run:
            caption: Pull latest
            command: git pull $PLAY_REMOTEREPO $PLAY_TARGETBRANCH
        - run:
            caption: Merge
            command: git merge --ff-only $PLAY_VER
    deploy:
      props:
      scene:
    validate-state:
      props:
      scene:
